// Footpaths, walkways and steps on the KKU campus for walking routes (owner request, 5 Oct 2026).
// Writes supabase/seed/footways.sql, which adds them to the existing road graph as foot-only
// segments (cars never use them) without touching roads, statuses or posts. Load it after roads.sql.
//
// Run:   NODE_USE_ENV_PROXY=1 npx tsx scripts/import-footways.ts   (data source: scripts/osm-campus.ts)
import { mkdirSync, writeFileSync } from 'node:fs';
import { lineLengthM, type LngLat } from '../lib/domain/geo';
import { campusOsm, type OsmWay } from './osm-campus';

const OUT = 'supabase/seed/footways.sql';
const FOOT = /^(footway|path|pedestrian|steps|cycleway|track|corridor|bridleway)$/;
const LINK_M = 30; // join a footpath to the nearest road node this close
const ID_BASE = 10_000_000; // footway node and segment ids start here (roads use small ids)

const q = (s: string | null | undefined) => (s ? `'${s.replace(/'/g, "''")}'` : 'null');
const pt = ([x, y]: LngLat) => `${x.toFixed(7)} ${y.toFixed(7)}`;

async function main() {
  const { nodes, ways, onCampus } = await campusOsm();
  const at = (id: number): LngLat => [nodes.get(id)!.lon, nodes.get(id)!.lat];
  const usable = (w: OsmWay) => w.nodes.every((n) => nodes.has(n)) && !/^(private|no)$/.test(w.tags?.access ?? '');
  const foot = [...ways.values()].filter((w) => FOOT.test(w.tags?.highway ?? '') && usable(w) && w.nodes.some((n) => onCampus(at(n))));
  const roads = [...ways.values()].filter((w) => w.tags?.highway && !FOOT.test(w.tags.highway));

  // Junctions: ends, and nodes shared with another footway or with a road.
  const uses = new Map<number, number>();
  for (const w of foot) for (const n of w.nodes) uses.set(n, (uses.get(n) ?? 0) + 1);
  const onRoad = new Set(roads.flatMap((w) => w.nodes));

  const keyOf = new Map<number, number>(); // OSM node → local key
  const nodeRows: string[] = [];
  const nodeKey = (osm: number) => {
    if (!keyOf.has(osm)) {
      const k = keyOf.size + 1;
      keyOf.set(osm, k);
      // Link to the road graph where a footpath meets a road or just ends.
      const link = onRoad.has(osm) || uses.get(osm) === 1;
      nodeRows.push(`(${k},'SRID=4326;POINT(${pt(at(osm))})',${link})`);
    }
    return keyOf.get(osm)!;
  };

  const segRows: string[] = [];
  for (const w of foot) {
    let start = 0;
    for (let i = 1; i < w.nodes.length; i++) {
      const n = w.nodes[i];
      if (i < w.nodes.length - 1 && (uses.get(n) ?? 0) < 2 && !onRoad.has(n)) continue;
      const line = w.nodes.slice(start, i + 1).map(at);
      const len = lineLengthM(line);
      if (len > 0.5)
        segRows.push(
          `(${segRows.length + 1},${nodeKey(w.nodes[start])},${nodeKey(n)},${q(w.tags!.highway)},${q(w.tags!.name)},${w.id},${len.toFixed(1)},` +
            `'SRID=4326;LINESTRING(${line.map(pt).join(',')})')`,
        );
      start = i;
    }
  }

  const chunk = (xs: string[], size = 1000) => Array.from({ length: Math.ceil(xs.length / size) }, (_, i) => xs.slice(i * size, (i + 1) * size));
  const sql = [
    `-- Generated by scripts/import-footways.ts on ${new Date().toISOString()} from OpenStreetMap (© OSM contributors, ODbL).`,
    '-- Adds campus footpaths to the road graph as foot-only segments. Safe to re-run; load after roads.sql.',
    'begin;',
    'delete from public.report_road_segments where segment_id in (select id from public.road_segments where foot_only);',
    'delete from public.road_segments where foot_only;',
    `delete from public.road_nodes where id >= ${ID_BASE};`,
    'create temp table fw_nodes (k int primary key, geom geometry(Point, 4326), link boolean, id bigint) on commit drop;',
    'create temp table fw_segs (k int, a int, b int, highway text, name text, osm_way_id bigint, length_m real, geom geometry(LineString, 4326)) on commit drop;',
    ...chunk(nodeRows).map((c) => `insert into fw_nodes (k, geom, link) values\n${c.join(',\n')};`),
    ...chunk(segRows).map((c) => `insert into fw_segs (k, a, b, highway, name, osm_way_id, length_m, geom) values\n${c.join(',\n')};`),
    '-- A footpath node on a road junction is that road node; the others are new.',
    `update fw_nodes f set id = coalesce((select r.id from public.road_nodes r where st_dwithin(r.geom, f.geom, 0.000002) order by r.geom <-> f.geom limit 1), ${ID_BASE} + f.k);`,
    `insert into public.road_nodes (id, geom) select id, geom from fw_nodes where id >= ${ID_BASE};`,
    `insert into public.road_segments (id, osm_way_id, name, highway, source, target, oneway, length_m, speed_kmh, geom, foot_only)
select ${ID_BASE} + s.k, s.osm_way_id, s.name, s.highway, a.id, b.id, false, s.length_m, 5, s.geom, true
from fw_segs s join fw_nodes a on a.k = s.a join fw_nodes b on b.k = s.b where a.id <> b.id;`,
    `-- Where a footpath meets a road between road nodes, or just ends, walk to the nearest road node.
insert into public.road_segments (id, osm_way_id, name, highway, source, target, oneway, length_m, speed_kmh, geom, foot_only)
select ${ID_BASE + 5_000_000} + f.k, null, null, 'footway', f.id, r.id, false,
  greatest(st_distance(f.geom::geography, r.geom::geography), 0.5), 5, st_makeline(f.geom, r.geom), true
from fw_nodes f cross join lateral (
  select id, geom from public.road_nodes where id < ${ID_BASE} order by geom <-> f.geom limit 1
) r
where f.link and f.id >= ${ID_BASE} and st_dwithin(f.geom::geography, r.geom::geography, ${LINK_M});`,
    'select public.mark_routable_nodes();',
    'commit;',
  ].join('\n');

  mkdirSync('supabase/seed', { recursive: true });
  writeFileSync(OUT, sql + '\n');
  console.log(`${foot.length} footways → ${segRows.length} segments, ${nodeRows.length} nodes → ${OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
