-- Core tables (PLAN §9, adapted for post clusters per PLAN §0).
-- Tunable numbers (radius limits, expiry, weights) live in lib/config.ts, not here:
-- all writes go through the API, which validates against that config.

create table public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  approved_count int not null default 0,
  rejected_count int not null default 0,
  banned boolean not null default false,
  created_at timestamptz not null default now()
);

-- Road graph for pgRouting, imported once from OSM (scripts/import-roads.ts).
create table public.road_nodes (
  id bigint primary key,
  geom geometry(Point, 4326) not null
);

create table public.road_segments (
  id bigint primary key,
  osm_way_id bigint,
  name text,
  highway text,
  source bigint not null references public.road_nodes,
  target bigint not null references public.road_nodes,
  oneway boolean not null default false,
  length_m real not null check (length_m > 0),
  speed_kmh real not null check (speed_kmh > 0),
  geom geometry(LineString, 4326) not null
);
create index road_segments_geom_idx on public.road_segments using gist (geom);
create index road_segments_source_idx on public.road_segments (source);
create index road_segments_target_idx on public.road_segments (target);
create index road_nodes_geom_idx on public.road_nodes using gist (geom);

create table public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles on delete cascade,
  kind text not null check (kind in ('area', 'road')),
  geom geometry(Point, 4326) not null,
  radius_m int check (radius_m > 0), -- area posts
  road_length_m real check (road_length_m > 0), -- road posts
  water_level text not null check (water_level in ('dry', 'puddle', 'ankle', 'knee', 'waist')),
  status_tags text[] not null default '{}'
    check (status_tags <@ array['raining', 'rising', 'receding', 'drain_overflow']),
  passability jsonb not null default '{}', -- {"motorcycle":"ok|hard|blocked", "car":…, "pickup":…, "walk":…}
  note text,
  photo_path text,
  poster_distance_m real, -- poster GPS to the reported point, at posting time
  elevation_m real, -- ground elevation at the point (low-lying factor, training data)
  rain_snapshot jsonb, -- {r1, r3, r24, r72, rainy_days} at posting time (training data)
  spam_score int not null default 0,
  spam_reasons text[] not null default '{}',
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'hidden', 'deleted')),
  still_votes int not null default 0, -- kept in sync by trigger
  receded_votes int not null default 0,
  last_still_vote_at timestamptz,
  flag_count int not null default 0,
  created_at timestamptz not null default now(),
  check ((kind = 'area') = (radius_m is not null)),
  check ((kind = 'road') = (road_length_m is not null))
);
create index reports_geom_idx on public.reports using gist (geom);
create index reports_active_idx on public.reports (status, created_at desc);
create index reports_user_idx on public.reports (user_id, created_at desc);

create table public.report_road_segments (
  report_id bigint references public.reports on delete cascade,
  segment_id bigint references public.road_segments,
  primary key (report_id, segment_id)
);

create table public.votes (
  report_id bigint references public.reports on delete cascade,
  user_id uuid references public.profiles on delete cascade,
  vote text not null check (vote in ('still', 'receded')),
  created_at timestamptz not null default now(),
  primary key (report_id, user_id)
);

create table public.post_flags (
  report_id bigint references public.reports on delete cascade,
  user_id uuid references public.profiles on delete cascade,
  reason text not null check (reason in ('false', 'spam', 'inappropriate', 'duplicate')),
  created_at timestamptz not null default now(),
  primary key (report_id, user_id)
);

create table public.rainfall (
  ts timestamptz primary key,
  r1 real not null,
  r3 real not null,
  r24 real not null,
  r72 real not null,
  rainy_days int not null,
  forecast_3h real not null,
  hourly real[] not null default '{}' -- last 12 hours, oldest first
);

-- Current flood circles (replaced on every refresh) and hourly history for training.
create table public.flood_clusters (
  id text primary key, -- 'c' || smallest report id in the group
  name text,
  center geometry(Point, 4326) not null,
  radius_m int not null,
  report_ids bigint[] not null,
  report_count int not null,
  low_factor real not null,
  base real not null,
  report real not null,
  c real not null,
  final real not null,
  weight_sum real not null,
  flooded boolean not null,
  updated_at timestamptz not null default now()
);
create index flood_clusters_center_idx on public.flood_clusters using gist (center);

create table public.flood_clusters_hourly (
  ts timestamptz not null,
  cluster_id text not null,
  center geometry(Point, 4326) not null,
  radius_m int not null,
  report_count int not null,
  low_factor real not null,
  base real not null,
  report real not null,
  c real not null,
  final real not null,
  rain_score real not null,
  primary key (ts, cluster_id)
);

-- Current road status per vehicle; segments without a row have no data.
create table public.segment_status (
  segment_id bigint references public.road_segments on delete cascade,
  vehicle text check (vehicle in ('motorcycle', 'car', 'pickup', 'walk')),
  status text not null check (status in ('ok', 'hard', 'blocked')),
  updated_at timestamptz not null default now(),
  primary key (segment_id, vehicle)
);

create table public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles,
  action text not null check (action in ('approve', 'reject', 'delete', 'restore', 'ban', 'unban')),
  target_type text not null check (target_type in ('report', 'user')),
  target_id text not null,
  note text,
  created_at timestamptz not null default now()
);

-- Fixed-window counters for per-IP / per-user limits (PLAN §7).
create table public.rate_limits (
  key text not null,
  window_start timestamptz not null,
  hits int not null default 0,
  primary key (key, window_start)
);
